### ISSUE TITLE
Purpose of Entities

### ISSUE THREAD

**Issue by lanthony42** [CSC207-UofT/course-project-aarves#44]
What is the point of entities if we have data persistence? How will we distinguish entities from DTOs from data persistence (i.e. what can entities do which won't be stored in a database)? Are entities basically just in-memory data storage for convenience more than anything?

**Comment by lanthony42** [comment]
Basically, we need to nail down the flow of data / control in our application.

**Comment by rebplane** [comment]
"Are entities basically just in-memory data storage for convenience more than anything?"
Pretty much, yes. 

The way I see it, the entities are mapped onto the database (each entity is stored in the database, the database only contains the attributes of the entity, so it's pretty much a one-to-one mapping).

On program startup, the data is loaded to entities to be able to modify them and use them (otherwise we would always need to go back to the database class through a gateway and sift through the information for what we need, rather than what we have now - controller -> use case -> entity to just grab what information we need/modify it).

DTO (if I understand it correctly) is an object that carries/transfer the data between processes - it does not have any uses other than simply serialization and deserialization. In comparison to entities, they do not contain any business logic. 

"Basically, we need to nail down the flow of data / control in our application."

I agree though. We'll use the other issue to discuss further on data transfer. We also need to figure out how we are presenting the data as well (which UI design pattern - MVP, MVC, MVVM? Are we doing this already?).

**Comment by lanthony42** [comment]
We should have another issue for sorting out UI Clean Architecture

**Comment by lanthony42** [comment]
The main issue is trying to differentiate DTOs and entities in our code to justify their (DTOs) existence as not just repeated code. Meaning, what exactly should our entities have in terms of "business logic"? Right now it seems a bit sparse.

**Comment by rebplane** [comment]
We have the entities ReviewList and AccountList, the databases accounts.json, reviews.json.

Just to clarify, what are the DTOs in our code right now (Account/ReviewSerializer?), or have we yet to add them into our code?

**Comment by lanthony42** [comment]
We need to add them so that our code adheres to Clean Architecture.

**Comment by lanthony42** [comment]
Discussion moved to #43.
